# 📈 Sales Forecasting Notebook - Day 1: Data Exploration

## 📦 Step 3: Import Libraries

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")
pd.set_option("display.max_columns", None)

## 📂 Step 4: Load the Dataset

In [2]:
train = pd.read_csv("../data/train.csv")
store = pd.read_csv("../data/store.csv")

## 👀 Step 5: Display the Data

In [3]:
print("--- Train Head ---")
display(train.head())

print("\n--- Store Head ---")
display(store.head())

--- Train Head ---

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,4,2015-01-01,3315,346,1,0,0,0
1,2,4,2015-01-01,4642,636,1,0,0,0
2,3,4,2015-01-01,4760,602,1,0,0,1
3,4,4,2015-01-01,8120,685,1,1,0,0
4,5,4,2015-01-01,10880,1049,1,0,0,0

--- Store Head ---

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,a,c,3000.0,7.0,2012.0,0,NaN,NaN,NaN
1,2,a,a,7500.0,5.0,2008.0,0,NaN,NaN,NaN
2,3,d,c,500.0,5.0,2012.0,1,10.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,a,a,1500.0,1.0,2010.0,1,40.0,2011.0,"Mar,Jun,Sept,Dec"
4,5,c,a,15000.0,NaN,2008.0,1,31.0,2009.0,"Mar,Jun,Sept,Dec"

In [4]:
print("--- Train Tail ---")
display(train.tail())

print("\n--- Store Tail ---")
display(store.tail())

--- Train Tail ---

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
9995,96,5,2015-04-10,7773,746,1,0,0,0
9996,97,5,2015-04-10,6806,802,1,0,0,0
9997,98,5,2015-04-10,6953,762,1,1,0,0
9998,99,5,2015-04-10,11895,1069,1,0,0,0
9999,100,5,2015-04-10,8269,656,1,1,0,0

--- Store Tail ---

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
95,96,d,c,500.0,7.0,2005.0,1,10.0,2009.0,"Feb,May,Aug,Nov"
96,97,c,a,120.0,NaN,2008.0,0,NaN,NaN,NaN
97,98,c,a,500.0,3.0,2008.0,1,10.0,2009.0,"Feb,May,Aug,Nov"
98,99,a,c,500.0,1.0,2012.0,0,NaN,NaN,NaN
99,100,b,c,500.0,9.0,2005.0,0,NaN,NaN,NaN

## 📐 Step 6: Dataset Shape

In [5]:
print("Train Shape:", train.shape)
print("Store Shape:", store.shape)

Train Shape: (10000, 9)
Store Shape: (100, 10)

## 📋 Step 7: Column Information

In [6]:
print("--- Train Info ---")
train.info()

print("\n--- Store Info ---")
store.info()

--- Train Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Store          10000 non-null  int64
 1   DayOfWeek      10000 non-null  int64
 2   Date           10000 non-null  object
 3   Sales          10000 non-null  int64
 4   Customers      10000 non-null  int64
 5   Open           10000 non-null  int64
 6   Promo          10000 non-null  int64
 7   StateHoliday   10000 non-null  int64
 8   SchoolHoliday  10000 non-null  int64
dtypes: int64(8), object(1)
memory usage: 703.3+ KB

--- Store Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      100 non-null    int64
 1   StoreType                  100 non-null    object
 2   Assortment                 100 non-null    object
 3   CompetitionDistance        94 non-null     float64
 4   CompetitionOpenSinceMonth  79 non-null     float64
 5   CompetitionOpenSinceYear   77 non-null     float64
 6   Promo2                     100 non-null    int64
 7   Promo2SinceWeek            49 non-null     float64
 8   Promo2SinceYear            49 non-null     float64
 9   PromoInterval              49 non-null     object
dtypes: float64(5), int64(2), object(3)
memory usage: 7.9+ KB

## 📝 Step 8: List the Columns

In [7]:
print("Train Columns:")
print(train.columns.tolist())

print("\nStore Columns:")
print(store.columns.tolist())

Train Columns:
['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday']

Store Columns:
['Store', 'StoreType', 'Assortment', 'CompetitionDistance', 'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2', 'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval']

## 📊 Step 9: Summary Statistics

In [8]:
print("--- Train Numerical Summary ---")
display(train.describe())

print("\n--- Store Numerical Summary ---")
display(store.describe())

--- Train Numerical Summary ---

,Store,DayOfWeek,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.0,10000.000000
mean,50.500000,4.010000,5800.374300,629.366400,0.843900,0.293100,0.0,0.197500
std,28.867513,1.982497,3551.946161,360.189154,0.362968,0.455207,0.0,0.398133
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,25.750000,2.000000,3614.500000,395.000000,1.000000,0.000000,0.0,0.000000
50%,50.500000,4.000000,5862.500000,665.000000,1.000000,0.000000,0.0,0.000000
75%,75.250000,6.000000,8248.000000,924.000000,1.000000,1.000000,0.0,0.000000
max,100.000000,7.000000,15332.000000,1199.000000,1.000000,1.000000,0.0,1.000000

--- Store Numerical Summary ---

,Store,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear
count,100.000000,94.000000,79.000000,77.000000,100.000000,49.000000,49.000000
mean,50.500000,2321.063830,5.506329,2009.870130,0.490000,21.102041,2011.612245
std,29.011492,3728.042373,3.426419,3.087968,0.502418,13.200765,2.352448
min,1.000000,120.000000,1.000000,2005.000000,0.000000,1.000000,2009.000000
25%,25.750000,500.000000,3.000000,2008.000000,0.000000,10.000000,2009.000000
50%,50.500000,1500.000000,5.000000,2010.000000,0.000000,22.000000,2011.000000
75%,75.250000,1500.000000,9.000000,2012.000000,1.000000,31.000000,2013.000000
max,100.000000,15000.000000,11.000000,2014.000000,1.000000,40.000000,2015.000000

In [9]:
print("--- Train All Columns Summary ---")
display(train.describe(include="all"))

print("\n--- Store All Columns Summary ---")
display(store.describe(include="all"))

--- Train All Columns Summary ---

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
count,10000.000000,10000.000000,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.0,10000.000000
unique,NaN,NaN,100,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,2015-01-01,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,100,NaN,NaN,NaN,NaN,NaN,NaN
mean,50.500000,4.010000,NaN,5800.374300,629.366400,0.843900,0.293100,0.0,0.197500
std,28.867513,1.982497,NaN,3551.946161,360.189154,0.362968,0.455207,0.0,0.398133
min,1.000000,1.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,25.750000,2.000000,NaN,3614.500000,395.000000,1.000000,0.000000,0.0,0.000000
50%,50.500000,4.000000,NaN,5862.500000,665.000000,1.000000,0.000000,0.0,0.000000
75%,75.250000,6.000000,NaN,8248.000000,924.000000,1.000000,1.000000,0.0,0.000000
max,100.000000,7.000000,NaN,15332.000000,1199.000000,1.000000,1.000000,0.0,1.000000

--- Store All Columns Summary ---

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
count,100.000000,100,100,94.000000,79.000000,77.000000,100.000000,49.000000,49.000000,49
unique,NaN,4,2,NaN,NaN,NaN,NaN,NaN,NaN,3
top,NaN,a,c,NaN,NaN,NaN,NaN,NaN,NaN,"Mar,Jun,Sept,Dec"
freq,NaN,52,54,NaN,NaN,NaN,NaN,NaN,NaN,20
mean,50.500000,NaN,NaN,2321.063830,5.506329,2009.870130,0.490000,21.102041,2011.612245,NaN
std,29.011492,NaN,NaN,3728.042373,3.426419,3.087968,0.502418,13.200765,2.352448,NaN
min,1.000000,NaN,NaN,120.000000,1.000000,2005.000000,0.000000,1.000000,2009.000000,NaN
25%,25.750000,NaN,NaN,500.000000,3.000000,2008.000000,0.000000,10.000000,2009.000000,NaN
50%,50.500000,NaN,NaN,1500.000000,5.000000,2010.000000,0.000000,22.000000,2011.000000,NaN
75%,75.250000,NaN,NaN,1500.000000,9.000000,2012.000000,1.000000,31.000000,2013.000000,NaN
max,100.000000,NaN,NaN,15000.000000,11.000000,2014.000000,1.000000,40.000000,2015.000000,NaN

## ❓ Step 10: Missing Values

In [10]:
print("Train Missing Values:\n", train.isnull().sum())
print("\nStore Missing Values:\n", store.isnull().sum())

print("\nTrain Columns with Missing Values:\n", train.isnull().sum()[train.isnull().sum() > 0])
print("\nStore Columns with Missing Values:\n", store.isnull().sum()[store.isnull().sum() > 0])

Train Missing Values:
 Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

Store Missing Values:
 Store                         0
StoreType                     0
Assortment                    0
CompetitionDistance           6
CompetitionOpenSinceMonth    21
CompetitionOpenSinceYear     23
Promo2                        0
Promo2SinceWeek              51
Promo2SinceYear              51
PromoInterval                51
dtype: int64

Train Columns with Missing Values:
 Series([], dtype: int64)

Store Columns with Missing Values:
 CompetitionDistance           6
CompetitionOpenSinceMonth    21
CompetitionOpenSinceYear     23
Promo2SinceWeek              51
Promo2SinceYear              51
PromoInterval                51
dtype: int64

## 🔁 Step 11: Duplicate Records

In [11]:
print("Train Duplicates:", train.duplicated().sum())
print("Store Duplicates:", store.duplicated().sum())

Train Duplicates: 0
Store Duplicates: 0

## 🧾 Step 12: Check Unique Values

In [12]:
print("Train Unique Values Count:")
display(train.nunique())

print("\nStore Unique Values Count:")
display(store.nunique())

Train Unique Values Count:

Store             100
DayOfWeek           7
Date              100
Sales            5745
Customers         901
Open                2
Promo               2
StateHoliday        1
SchoolHoliday       2
dtype: int64

Store Unique Values Count:

Store                        100
StoreType                      4
Assortment                     2
CompetitionDistance            6
CompetitionOpenSinceMonth      6
CompetitionOpenSinceYear       5
Promo2                         2
Promo2SinceWeek                6
Promo2SinceYear                4
PromoInterval                  3
dtype: int64

## 📚 Step 13: Understand the Features

### `train.csv`
| Column | Description |
|---|---|
| **Store** | Store ID |
| **DayOfWeek** | Day of the week (1–7) |
| **Date** | Sales date |
| **Sales** | Daily sales (Target) |
| **Customers** | Number of customers |
| **Open** | Store open (1) or closed (0) |
| **Promo** | Promotion running (1) or not (0) |
| **StateHoliday** | State holiday indicator |
| **SchoolHoliday** | School holiday indicator |

### `store.csv`
| Column | Description |
|---|---|
| **Store** | Store ID |
| **StoreType** | Type of store |
| **Assortment** | Assortment level |
| **CompetitionDistance** | Distance to nearest competitor |
| **CompetitionOpenSinceMonth** | Competition opening month |
| **CompetitionOpenSinceYear** | Competition opening year |
| **Promo2** | Continuous promotion flag |
| **Promo2SinceWeek** | Promotion start week |
| **Promo2SinceYear** | Promotion start year |
| **PromoInterval** | Promotion interval |

# Day 1 Summary

## Dataset Overview

- Loaded train.csv and store.csv successfully.
- Explored dataset dimensions.
- Reviewed column names and data types.
- Checked for missing values and duplicates.
- Generated descriptive statistics.
- Understood the purpose of each feature.

## Key Observations

- The train dataset contains daily sales records for multiple stores.
- The store dataset contains static information about each store.
- Some columns in store.csv contain missing values that will be handled during data cleaning.
- The Sales column will be our target variable for forecasting.

# 🧹 Day 2: Data Cleaning & Data Preparation

## 🔀 Step 1: Merge the Datasets

In [13]:
# Merge train and store datasets
df = train.merge(store, on="Store", how="left")

print("Merged Dataset Shape:", df.shape)
display(df.head())

Merged Dataset Shape:

 (10000, 18)

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,4,2015-01-01,3315,346,1,0,0,0,a,c,3000.0,7.0,2012.0,0,NaN,NaN,NaN
1,2,4,2015-01-01,4642,636,1,0,0,0,a,a,7500.0,5.0,2008.0,0,NaN,NaN,NaN
2,3,4,2015-01-01,4760,602,1,0,0,1,d,c,500.0,5.0,2012.0,1,10.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,4,2015-01-01,8120,685,1,1,0,0,a,a,1500.0,1.0,2010.0,1,40.0,2011.0,"Mar,Jun,Sept,Dec"
4,5,4,2015-01-01,10880,1049,1,0,0,0,c,a,15000.0,NaN,2008.0,1,31.0,2009.0,"Mar,Jun,Sept,Dec"

## ❓ Step 2: Check Missing Values

In [14]:
missing = df.isnull().sum().sort_values(ascending=False)
missing = missing[missing > 0]

missing_percentage = (df.isnull().sum() / len(df)) * 100
missing_percentage = missing_percentage[missing_percentage > 0]

missing_df = pd.DataFrame({
    "Missing Values": missing,
    "Percentage": missing_percentage
})
display(missing_df)

                           Missing Values  Percentage
CompetitionDistance                   600         6.0
CompetitionOpenSinceMonth            2100        21.0
CompetitionOpenSinceYear             2300        23.0
Promo2SinceWeek                      5100        51.0
Promo2SinceYear                      5100        51.0
PromoInterval                        5100        51.0

## 🛠️ Step 3: Handle Missing Values

In [15]:
# Competition distance
df["CompetitionDistance"] = df["CompetitionDistance"].fillna(df["CompetitionDistance"].median())

# Competition opening month/year
df["CompetitionOpenSinceMonth"] = df["CompetitionOpenSinceMonth"].fillna(0)
df["CompetitionOpenSinceYear"] = df["CompetitionOpenSinceYear"].fillna(0)

# Promo2 information
df["Promo2SinceWeek"] = df["Promo2SinceWeek"].fillna(0)
df["Promo2SinceYear"] = df["Promo2SinceYear"].fillna(0)
df["PromoInterval"] = df["PromoInterval"].fillna("None")

print("Remaining Missing Values:")
display(df.isnull().sum()[df.isnull().sum() > 0])

Remaining Missing Values:

Series([], dtype: int64)

## 🔁 Step 4: Check Duplicates

In [16]:
print("Duplicate Rows:", df.duplicated().sum())

if df.duplicated().sum() > 0:
    df.drop_duplicates(inplace=True)
    print("New Shape:", df.shape)

Duplicate Rows: 0

## 📅 Step 5: Convert Date Column

In [17]:
df["Date"] = pd.to_datetime(df["Date"])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      10000 non-null  int64
 1   DayOfWeek                  10000 non-null  int64
 2   Date                       10000 non-null  datetime64[ns]
 3   Sales                      10000 non-null  int64
 4   Customers                  10000 non-null  int64
 5   Open                       10000 non-null  int64
 6   Promo                      10000 non-null  int64
 7   StateHoliday               10000 non-null  int64
 8   SchoolHoliday              10000 non-null  int64
 9   StoreType                  10000 non-null  object
 10  Assortment                 10000 non-null  object
 11  CompetitionDistance        10000 non-null  float64
 12  CompetitionOpenSinceMonth  10000 non-null  float64
 13  CompetitionOpenSinceYear   10000 non-null  float64
 14  Promo2                     10000 non-null  int64
 15  Promo2SinceWeek            10000 non-null  float64
 16  Promo2SinceYear            10000 non-null  float64
 17  PromoInterval              10000 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(9), object(3)
memory usage: 1.4+ MB

## ⏱️ Step 6: Create Date Features

In [18]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["Week"] = df["Date"].dt.isocalendar().week.astype(int)
df["Quarter"] = df["Date"].dt.quarter
df["DayName"] = df["Date"].dt.day_name()

display(df[["Date", "Year", "Month", "Day", "Week", "Quarter", "DayName"]].head())

        Date  Year  Month  Day  Week  Quarter   DayName
0 2015-01-01  2015      1    1     1        1  Thursday
1 2015-01-01  2015      1    1     1        1  Thursday
2 2015-01-01  2015      1    1     1        1  Thursday
3 2015-01-01  2015      1    1     1        1  Thursday
4 2015-01-01  2015      1    1     1        1  Thursday

## 🔍 Step 7: Verify Data Types

In [19]:
display(df.dtypes)

Store                                 int64
DayOfWeek                             int64
Date                         datetime64[ns]
Sales                                 int64
Customers                             int64
Open                                  int64
Promo                                 int64
StateHoliday                          int64
SchoolHoliday                         int64
StoreType                            object
Assortment                           object
CompetitionDistance                 float64
CompetitionOpenSinceMonth           float64
CompetitionOpenSinceYear            float64
Promo2                                int64
Promo2SinceWeek                     float64
Promo2SinceYear                     float64
PromoInterval                        object
Year                                  int32
Month                                 int32
Day                                   int32
Week                                  int64
Quarter                               int32
DayName                              object
dtype: object

## 🧾 Step 8: Check Unique Values

In [20]:
for col in ["StoreType", "Assortment", "StateHoliday", "Promo2"]:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())

--- StoreType ---
StoreType
a    5200
d    3500
c    1200
b     100
Name: count, dtype: int64

--- Assortment ---
Assortment
c    5400
a    4600
Name: count, dtype: int64

--- StateHoliday ---
StateHoliday
0    10000
Name: count, dtype: int64

--- Promo2 ---
Promo2
0    5100
1    4900
Name: count, dtype: int64

## 📌 Step 9: Final Dataset Overview

In [21]:
print("Final Cleaned Dataset Shape:", df.shape)

display(df.head())

Final Cleaned Dataset Shape: (10000, 24)

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval,Year,Month,Day,Week,Quarter,DayName
0,1,4,2015-01-01,3315,346,1,0,0,0,a,c,3000.0,7.0,2012.0,0,0.0,0.0,None,2015,1,1,1,1,Thursday
1,2,4,2015-01-01,4642,636,1,0,0,0,a,a,7500.0,5.0,2008.0,0,0.0,0.0,None,2015,1,1,1,1,Thursday
2,3,4,2015-01-01,4760,602,1,0,0,1,d,c,500.0,5.0,2012.0,1,10.0,2011.0,"Jan,Apr,Jul,Oct",2015,1,1,1,1,Thursday
3,4,4,2015-01-01,8120,685,1,1,0,0,a,a,1500.0,1.0,2010.0,1,40.0,2011.0,"Mar,Jun,Sept,Dec",2015,1,1,1,1,Thursday
4,5,4,2015-01-01,10880,1049,1,0,0,0,c,a,15000.0,0.0,2008.0,1,31.0,2009.0,"Mar,Jun,Sept,Dec",2015,1,1,1,1,Thursday

## 💾 Step 10: Save the Cleaned Dataset

In [22]:
import os
os.makedirs("../data", exist_ok=True)
df.to_csv("../data/processed_sales.csv", index=False)
print("Cleaned dataset successfully saved to ../data/processed_sales.csv")

Cleaned dataset successfully saved to ../data/processed_sales.csv

# Day 2 Summary

## Data Cleaning

- Merged train and store datasets.
- Handled missing values using median and default values.
- Removed duplicate records.
- Converted the Date column to datetime format.
- Created new time-based features:
  - Year
  - Month
  - Day
  - Week
  - Quarter
  - DayName
- Saved the cleaned dataset for further analysis.

## Outcome

The dataset is now clean and enriched with additional features, making it ready for Exploratory Data Analysis (EDA).